"""
Bootstrap the repo for running experiments on Vast.

Examples:
  python baseline/utils/vast_setup.py
  python baseline/utils/vast_setup.py --skip-vast-start
"""

from __future__ import annotations

import argparse
import getpass
import os
import shlex
import subprocess
import sys
import venv
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from baseline.utils.vast import resolve_vast_api_key, resolve_vast_instance_id

DEFAULT_PYTORCH_ALLOC_CONF = "expandable_segments:True"
DEFAULT_ENV_FILE = ".env.vast"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create or reuse .venv, install requirements, persist Vast/W&B env vars, "
            "and validate the Vast CLI in-container control path."
        )
    )
    parser.add_argument(
        "--env-file",
        default=DEFAULT_ENV_FILE,
        help="Repo-local shell file where exported env vars are written.",
    )
    parser.add_argument(
        "--skip-install",
        action="store_true",
        help="Skip .venv creation and pip installation steps.",
    )
    parser.add_argument(
        "--skip-vast-start",
        action="store_true",
        help="Skip the `vastai start instance` validation call.",
    )
    return parser.parse_args(argv)


def _render_command(command: list[str]) -> str:
    return " ".join(shlex.quote(part) for part in command)


def _run_checked(*, command: list[str], cwd: Path, env: dict[str, str] | None = None) -> None:
    print(f"[vast-setup] running: {_render_command(command)}")
    subprocess.run(command, cwd=cwd, env=env, check=True)


def _prompt_secret(env_key: str) -> str:
    print(f"[vast-setup] {env_key} is not set; prompting for input.")
    if not sys.stdin.isatty():
        raise RuntimeError(
            f"{env_key} is not set and no interactive TTY is available. "
            f"Set {env_key} before running the setup script."
        )

    while True:
        entered = getpass.getpass(f"Enter {env_key}: ").strip()
        if entered:
            return entered
        print(f"{env_key} cannot be empty.", file=sys.stderr)


def _ensure_venv(venv_dir: Path) -> Path:
    python_path = venv_dir / "bin" / "python"
    if python_path.exists():
        return python_path

    print(f"[vast-setup] creating virtual environment at {venv_dir}")
    venv.EnvBuilder(with_pip=True).create(venv_dir)
    return python_path


def _write_env_file(path: Path, exports: dict[str, str]) -> None:
    lines = [
        "# Generated by baseline/utils/vast_setup.py",
        "# Source this file to load repo-local Vast/W&B environment variables.",
    ]
    for key, value in exports.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o600)


def _prepare_exports(repo_root: Path) -> tuple[dict[str, str], dict[str, str]]:
    ambient_env = dict(os.environ)
    exports: dict[str, str] = {}
    summary: dict[str, str] = {}

    wandb_api_key = ambient_env.get("WANDB_API_KEY", "").strip()
    if not wandb_api_key:
        wandb_api_key = _prompt_secret("WANDB_API_KEY")
        summary["WANDB_API_KEY"] = "prompted"
    else:
        summary["WANDB_API_KEY"] = "existing"
    exports["WANDB_API_KEY"] = wandb_api_key

    vast_api_key, vast_api_key_source = resolve_vast_api_key(ambient_env)
    if not vast_api_key:
        vast_api_key = _prompt_secret("VAST_API_KEY")
        vast_api_key_source = "prompted"
    exports["VAST_API_KEY"] = vast_api_key
    summary["VAST_API_KEY"] = vast_api_key_source or "prompted"

    try:
        container_id, container_id_source = resolve_vast_instance_id(ambient_env)
    except ValueError as exc:
        raise RuntimeError(str(exc)) from exc
    if container_id is not None:
        exports["CONTAINER_ID"] = str(container_id)
        summary["CONTAINER_ID"] = container_id_source or "existing"

    # wandb_data_dir = ambient_env.get("WANDB_DATA_DIR", "").strip()
    # if not wandb_data_dir:
    #     wandb_data_dir = str((repo_root / ".wandb-data").resolve())
    #     summary["WANDB_DATA_DIR"] = "defaulted"
    # else:
    #     summary["WANDB_DATA_DIR"] = "existing"
    # exports["WANDB_DATA_DIR"] = wandb_data_dir

    pytorch_alloc_conf = ambient_env.get("PYTORCH_ALLOC_CONF", "").strip()
    if not pytorch_alloc_conf:
        pytorch_alloc_conf = DEFAULT_PYTORCH_ALLOC_CONF
        summary["PYTORCH_ALLOC_CONF"] = "defaulted"
    else:
        summary["PYTORCH_ALLOC_CONF"] = "existing"
    exports["PYTORCH_ALLOC_CONF"] = pytorch_alloc_conf

    return exports, summary


def main(argv: list[str] | None = None) -> int:
    args = parse_args(list(sys.argv[1:] if argv is None else argv))

    repo_root = PROJECT_ROOT
    env_file = repo_root / args.env_file
    venv_dir = repo_root / ".venv"
    python_path = venv_dir / "bin" / "python"
    vastai_path = venv_dir / "bin" / "vastai"

    if not args.skip_install:
        python_path = _ensure_venv(venv_dir)
        _run_checked(
            command=[str(python_path), "-m", "pip", "install", "-r", "requirements.txt"],
            cwd=repo_root,
        )

    for directory in (
        repo_root / ".wandb-data",
        repo_root / "runs" / "logs",
        repo_root / "baseline" / "models",
    ):
        directory.mkdir(parents=True, exist_ok=True)

    exports, summary = _prepare_exports(repo_root)
    _write_env_file(env_file, exports)
    print(f"[vast-setup] wrote {env_file}")

    validation_env = dict(os.environ)
    validation_env.update(exports)
    if not args.skip_vast_start:
        container_id = exports.get("CONTAINER_ID")
        if container_id:
            if not vastai_path.exists():
                raise RuntimeError(
                    f"Expected Vast CLI at {vastai_path}. "
                    "Install dependencies or rerun without --skip-install."
                )
            _run_checked(
                command=[str(vastai_path), "start", "instance", container_id],
                cwd=repo_root,
                env=validation_env,
            )
        else:
            print(
                "[vast-setup] CONTAINER_ID/VAST_CONTAINERLABEL not set; "
                "skipping `vastai start instance` validation."
            )

    print("[vast-setup] setup complete")
    for key, source in sorted(summary.items()):
        print(f"[vast-setup] {key} source={source}")
    print(f"[vast-setup] source {env_file} before launching experiments")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
